name: Deploy Frontend to Hostinger

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{secrets.SSH_HOST}}
                username: ${{secrets.SSH_USERNAME}}
                key: ${{secrets.SSH_KEY}}
                script: |
                    set -e
                    cd /root/project_x-frontend

                    git remote remove origin || true
                    git remote add origin https://github.com/Tushar-CodeSpace/project_x-frontend.git

                    git fetch origin
                    git reset --hard origin/main

                    docker compose up -d --build